# Start your image with a node base image
FROM node:18-alpine

# create application directory
RUN mkdir -p /app 

# The /app directory should act as the main application directory
WORKDIR /app

EXPOSE 3000